### ISSUE TITLE
Xsd choice boolean invalid occurrence 

### ISSUE THREAD

**Issue by akbence** [icellmobilsoft/openapi-jaxb#14]
##  Explaining the problem

Consider, we have the following XSD:
```xml
            <xs:choice>
                <xs:element name="somebool" type="xs:boolean">
                    <xs:annotation>
                        <xs:documentation xml:lang="en">TESTBOOL</xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element name="someBool2" type="xs:boolean">
                    <xs:annotation>
                        <xs:documentation xml:lang="en">TESTBOOL2</xs:documentation>
                    </xs:annotation>
                </xs:element>
            </xs:choice>

```
With this snippet the following openapi document is generated:

```
        somebool:
          title: somebool
          description: TESZTBOOOL
          type: boolean
        someBool2:
          title: someBool2
          description: TESZTBOOL2
          type: boolean

```

When there is an <xs:choice> </xs:choice> field declared, the openapi shows, that either values are part of the structure, which is a false statement, in the view of validation. It is a limitation, therefore it needs a fix.

## Workaround

In this example, there is a workaround. If the openapi, could show, that _somebool_ could be either null, or a valid value, that would be a better solution, than this, right now. If we add _minOccurs="0"_ to the element, we could extract that to use it as a new property: nullable:false/true

In this situation (with the bool element) it would show the following:

```
        somebool:
          title: somebool
          description: TESZTBOOOL
          type: boolean
          nullable: true
        someBool2:
          title: someBool2
          description: TESZTBOOL2
          type: boolean
          nullable: true
```

```java
protected void addNullableProperty(JAnnotationUse apiProperty, CClassInfo targetClass, String propertyName) {
        CPropertyInfo property = targetClass.getProperty(propertyName);
        XSComponent schemaComponent = property.getSchemaComponent();
        if (schemaComponent instanceof XSParticle) {
            XSParticle particle = (XSParticle) schemaComponent;
            BigInteger minOccurs = particle.getMinOccurs();
            if (minOccurs.equals(BigInteger.ZERO)) {
                apiProperty.param(SchemaFields.NULLABLE, true);
            }
        }
    }
```

It is a workaround only, because the requirement can be, that either value have to be there, and this XSD says, it wont.
It is not the best solution, it needs a deeper research

## Best solution

If there would be a way, to extract, if an XSParticle is a part of choice, then there can be a new property (or the _nullable_), to tell it is in a XOR relation with the other part(s) of the choice.

Important note: Despite the issue's name, this problem is not unique to boolean's only.

**Comment by petrenyi-mark** [comment]
Yeah, right now the plugin can not handle choices.
I wouldn't go with the workaround as it could be confusing calling choice elements as nullable.
Actually I think the choice should be represented with the use of "oneOf" attribute
So instead of this:
```yml
    dto:
      properties:
        someSequenceProp:
          ...
        somebool:
          title: somebool
          description: TESZTBOOOL
          type: boolean
        someBool2:
          title: someBool2
          description: TESZTBOOL2
          type: boolean
```
the openapi yaml should be generated like this:
```yml
    dto:
      allOf:
        - properties: #We need everything from here
            someSequenceProp:
              ...
        - oneOf: #and we need exactly one of these
          - properties:
              somebool:
                title: somebool
                description: TESZTBOOOL
                type: boolean
          - properties:
              someBool2:
                title: someBool2
                description: TESZTBOOL2
                type: boolean
```
Unfortunately `org.eclipse.microprofile.openapi.annotations.media.Schema` annotation expects `Class<?>[]` to be set into oneOf and allOf so in order to achieve a document like the above we would need multiple classes generated from the same xsd type (one "common" class for the seqenced elements, and one class for each element enclosed in a choice). It would be overcomplicated, and could possibly break jaxb processing..

One viable solution would be to use an extension as you suggested (i would go with `x-xhoice` or something similar) to mark which properties are present in the same choice. ie.:
```java
@Schema(name = "dto", description = "dto complex type")
public class Dto implements Serializable
{

    @XmlElement(required = true)
    @Schema(name = "someSequenceProp")
    protected String someSequenceProp;

    @Schema(name = "somebool", title = "somebool", description = "TESZTBOOOL", required = true)
    @Extension(name = "x-choice", value="45E2X7CDB4TSRTG3") //value should be some generated id representing a choice (this would help separating multiple choices in the same type decalration)
    protected boolean somebool;

    @Schema(name = "someBool2", title = "someBool2", description = "TESZTBOOL2", required = true)
    @Extension(name = "x-choice", value="45E2X7CDB4TSRTG3") //value is the same, since someBool and someBool2 are in the same choice
    protected boolean someBool2;

    //getters,setters
}
```

Then we could implement an `OASFilter` to move the marked properties into the `oneOf` list (it needs further research if such modification is possible using the filter).

NOTE: right now not every mp-openapi implementation can handle `@Extension` annotations on class fields; this could hinder this solution.
